Name: NetworkSettingsWidgetComponents
Type: FolderType
Children:
- Name: LAN
  Id: g=41f433c486aa6dfdb14c2c47570eea1a
  Supertype: Panel
  ReferenceType: HasComponent
  Children:
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 244.0
  - Name: DHCPClientEnabledCheckbox
    Type: CheckBox
    Children:
    - Name: Checked
      Type: BaseDataVariableType
      DataType: Boolean
      Value: true
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DHCPClientEnabled"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 14.0
  - Name: IPAddressLabel
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"IPAddress"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 46.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: IPAddressTextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 65.0
  - Name: MaskLabel
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"Mask"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 46.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: MaskTextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 145.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 65.0
  - Name: DefaultGatewayLayout
    Type: ColumnLayout
    Children:
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 60.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 266.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 30.0
    - Name: DefaultGatewayLabel
      Type: Label
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        ModellingRule: Optional
        Value: {"NamespaceIndex":18,"TextId":"DefaultGateway"}
      - Name: FontFamily
        Type: BaseDataVariableType
        DataType: Font
        ModellingRule: Optional
        Value: ""
      - Name: TextHorizontalAlignment
        Type: BaseVariableType
        DataType: TextHorizontalAlignment
        ModellingRule: Optional
        Value: 0
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 3
      - Name: WordWrap
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
      - Name: VerticalAlignment
        Type: BaseVariableType
        DataType: VerticalAlignment
        ModellingRule: Optional
        Value: 1
      - Name: BottomMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 4.0
    - Name: DefaultGatewayTextBox
      Type: TextBox
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        Value: {"LocaleId":"en-US","Text":""}
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 3
    - Name: ContentAlignment
      Type: BaseVariableType
      DataType: ContentVerticalAlignment
      ModellingRule: Optional
      Value: 2
  - Name: DNS1Label
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DNS1"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 96.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: DNS1TextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 114.0
  - Name: DNS2Label
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DNS2"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 96.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: DNS2TextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 114.0
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
    Value: 3
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
    Value: 3
- Name: WAN
  Id: g=d17d8ab3d7f8047c35a02cbe0b7248c6
  Supertype: Panel
  ReferenceType: HasComponent
  Children:
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 244.0
  - Name: DHCPClientEnabledCheckbox
    Type: CheckBox
    Children:
    - Name: Checked
      Type: BaseDataVariableType
      DataType: Boolean
      Value: true
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DHCPClientEnabled"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 14.0
  - Name: IPAddressLabel
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"IPAddress"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 46.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: IPAddressTextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 65.0
    - Name: Enabled
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
  - Name: MaskLabel
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"Mask"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 46.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: MaskTextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 145.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 65.0
    - Name: Enabled
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
  - Name: DefaultGatewayLayout
    Type: ColumnLayout
    Children:
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 60.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 266.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 30.0
    - Name: ContentAlignment
      Type: BaseVariableType
      DataType: ContentVerticalAlignment
      ModellingRule: Optional
      Value: 2
    - Name: DefaultGatewayLabel
      Type: Label
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        ModellingRule: Optional
        Value: {"NamespaceIndex":18,"TextId":"DefaultGateway"}
      - Name: FontFamily
        Type: BaseDataVariableType
        DataType: Font
        ModellingRule: Optional
        Value: ""
      - Name: TextHorizontalAlignment
        Type: BaseVariableType
        DataType: TextHorizontalAlignment
        ModellingRule: Optional
        Value: 0
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 3
      - Name: VerticalAlignment
        Type: BaseVariableType
        DataType: VerticalAlignment
        ModellingRule: Optional
        Value: 1
      - Name: WordWrap
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
    - Name: DefaultGatewayTextBox
      Type: TextBox
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        Value: {"LocaleId":"en-US","Text":""}
      - Name: Enabled
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 4.0
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 3
  - Name: DNS1Label
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DNS1"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 96.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: DNS1TextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 24.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 114.0
    - Name: Enabled
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
  - Name: DNS2Label
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":18,"TextId":"DNS2"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 96.0
    - Name: FontFamily
      Type: BaseDataVariableType
      DataType: Font
      ModellingRule: Optional
      Value: ""
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 0
  - Name: DNS2TextBox
    Type: TextBox
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"LocaleId":"en-US","Text":""}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 110.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 146.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 114.0
    - Name: Enabled
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
    Value: 3
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
    Value: 3
