Name: NetworkSettingsWidget
Type: FolderType
Children:
- Name: NetworkSettingsWidget
  Id: g=93cbf19dd68a72c543a41f03c3c2b7a1
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 250.0
  - Name: NavigationPanel1
    Type: NavigationPanel
    Children:
    - Name: Panels
      Type: BaseObjectType
      Children:
      - Name: LANPanel
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"LAN"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/optix_example/UI/SettingsWidgets/NetworkSettingsWidget/NetworkSettingsWidgetComponents/LAN"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item/Container"
      - Name: WANPanel
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"WAN"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/optix_example/UI/SettingsWidgets/NetworkSettingsWidget/NetworkSettingsWidgetComponents/WAN"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item/Container"
    - Name: CurrentPanel
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Children:
      - Name: Kind
        Type: PropertyType
        DataType: NodeId
        Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item"
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 304.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 200.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TabPosition
      Type: BaseVariableType
      DataType: NavigationPanelTabPositionEnum
      ModellingRule: Optional
    - Name: CurrentTabIndex
      Type: BaseDataVariableType
      DataType: Int32
    - Class: Reference
      Target: ns=5;i=1181
    - Class: Reference
      Target: ns=5;i=1183
  - Name: BottomBar
    Type: Panel
    Children:
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 400.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 56.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 195.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: Separator
      Type: PolyLine
      Children:
      - Name: LineColor
        Type: BaseDataVariableType
        DataType: Color
        ModellingRule: Optional
        Value: "#d2ddee"
      - Name: FillColor
        Type: BaseDataVariableType
        DataType: Color
        ModellingRule: Optional
        Value: "#ffffff"
      - Name: LineThickness
        Type: BaseDataVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 1.0
      - Name: Blink
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
      - Name: Path
        Type: BaseDataVariableType
        DataType: String
        ModellingRule: Optional
        Value: "M 0.000000 0.000000 L 332.000000 0.000000"
      - Name: HitTestVisible
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
      - Name: MoveTarget
        Type: NodePointer
        DataType: NodeId
        ModellingRule: Optional
        Children:
        - Name: Kind
          Type: PropertyType
          DataType: NodeId
          Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item/Container"
        - Name: NodeClass
          Type: PropertyType
          DataType: NodePointerNodeClass
          ModellingRule: Optional
          Value: 2
      - Name: Visible
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
      - Name: Enabled
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
      - Name: Opacity
        Type: BaseVariableType
        DataType: Float
        ModellingRule: Optional
        Value: 100.0
      - Name: LeftMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 24.0
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 5.0
      - Name: RightMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
      - Name: BottomMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
      - Name: Width
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 360.0
      - Name: Height
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 1.0
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
      - Name: VerticalAlignment
        Type: BaseVariableType
        DataType: VerticalAlignment
        ModellingRule: Optional
      - Name: Rotation
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
    - Name: RebootButton
      Type: Button
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        ModellingRule: Optional
        Value: {"NamespaceIndex":18,"TextId":"Reboot"}
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 13.0
      - Name: Height
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 34.0
      - Name: Width
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 80.0
      - Name: MouseClickEventHandler1
        Type: EventHandler
        Children:
        - Name: ListenEventType
          Type: PropertyType
          DataType: NodeId
          Value: "/Types/EventTypes/BaseEventType/MouseEvent/MouseClickEvent"
        - Name: MethodsToCall
          Type: BaseObjectType
          Children:
          - Name: MethodContainer1
            Type: BaseObjectType
            Children:
            - Name: ns=3;ObjectPointer
              Type: NodePointer
              DataType: NodeId
              Children:
              - Name: Kind
                Type: PropertyType
                DataType: NodeId
                Value: "/Types/ObjectTypes/BaseObjectType"
              - Name: DynamicLink
                Type: DynamicLink
                DataType: NodePath
                Value: "../../../../../../NetworkSettingsLogic@NodeId"
                Children:
                - Name: Mode
                  Type: BaseVariableType
                  DataType: DynamicLinkMode
                  ModellingRule: Optional
                  Value: 2
            - Name: ns=3;Method
              Type: BaseDataVariableType
              DataType: String
              Value: "Reboot"
        - Name: EventArguments
          Type: MouseClickEvent
          Children:
          - Name: EventId
            Type: PropertyType
            DataType: ByteString
          - Name: EventType
            Type: PropertyType
            DataType: NodeId
          - Name: SourceNode
            Type: PropertyType
            DataType: NodeId
          - Name: SourceName
            Type: PropertyType
            DataType: String
          - Name: Time
            Type: PropertyType
            DataType: UtcTime
          - Name: ReceiveTime
            Type: PropertyType
            DataType: UtcTime
          - Name: Message
            Type: PropertyType
            DataType: LocalizedText
          - Name: Severity
            Type: PropertyType
            DataType: UInt16
      - Name: Enabled
        Type: BaseDataVariableType
        DataType: Boolean
        Value: true
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 1
      - Name: RightMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 8.0
    - Name: ApplyButton
      Type: Button
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        ModellingRule: Optional
        Value: {"NamespaceIndex":18,"TextId":"Apply"}
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 13.0
      - Name: Height
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 34.0
      - Name: Width
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 72.0
      - Name: MouseClickEventHandler1
        Type: EventHandler
        Children:
        - Name: ListenEventType
          Type: PropertyType
          DataType: NodeId
          Value: "/Types/EventTypes/BaseEventType/MouseEvent/MouseClickEvent"
        - Name: MethodsToCall
          Type: BaseObjectType
          Children:
          - Name: MethodContainer1
            Type: BaseObjectType
            Children:
            - Name: ns=3;ObjectPointer
              Type: NodePointer
              DataType: NodeId
              Children:
              - Name: Kind
                Type: PropertyType
                DataType: NodeId
                Value: "/Types/ObjectTypes/BaseObjectType"
              - Name: DynamicLink
                Type: DynamicLink
                DataType: NodePath
                Value: "../../../../../../NetworkSettingsLogic@NodeId"
                Children:
                - Name: Mode
                  Type: BaseVariableType
                  DataType: DynamicLinkMode
                  ModellingRule: Optional
                  Value: 2
            - Name: ns=3;Method
              Type: BaseDataVariableType
              DataType: String
              Value: "ApplyNetworkConfiguration"
        - Name: EventArguments
          Type: MouseClickEvent
          Children:
          - Name: EventId
            Type: PropertyType
            DataType: ByteString
          - Name: EventType
            Type: PropertyType
            DataType: NodeId
          - Name: SourceNode
            Type: PropertyType
            DataType: NodeId
          - Name: SourceName
            Type: PropertyType
            DataType: String
          - Name: Time
            Type: PropertyType
            DataType: UtcTime
          - Name: ReceiveTime
            Type: PropertyType
            DataType: UtcTime
          - Name: Message
            Type: PropertyType
            DataType: LocalizedText
          - Name: Severity
            Type: PropertyType
            DataType: UInt16
      - Name: HorizontalAlignment
        Type: BaseVariableType
        DataType: HorizontalAlignment
        ModellingRule: Optional
        Value: 1
      - Name: RightMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 96.0
    - Name: WarningImage
      Type: Image
      Children:
      - Name: Path
        Type: BaseDataVariableType
        DataType: ResourceUri
        Value: "ns=18;%PROJECTDIR%/WarningIcon.svg"
      - Name: Width
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 16.0
      - Name: Height
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 16.0
      - Name: LeftMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 10.0
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 19.0
      - Name: Visible
        Type: BaseDataVariableType
        DataType: Boolean
    - Name: MessageLabel
      Type: Label
      Children:
      - Name: Text
        Type: BaseDataVariableType
        DataType: LocalizedText
        ModellingRule: Optional
        Value: {"NamespaceIndex":18,"TextId":"RebootToCommitChanges"}
      - Name: LeftMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 32.0
      - Name: Visible
        Type: BaseDataVariableType
        DataType: Boolean
        Value: true
      - Name: VerticalAlignment
        Type: BaseVariableType
        DataType: VerticalAlignment
        ModellingRule: Optional
        Value: 2
      - Name: TopMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: -2.0
      - Name: BottomMargin
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
      - Name: Elide
        Type: BaseDataVariableType
        DataType: ElideEnum
        ModellingRule: Optional
      - Name: WordWrap
        Type: BaseDataVariableType
        DataType: Boolean
        ModellingRule: Optional
        Value: true
      - Name: Width
        Type: BaseVariableType
        DataType: Size
        ModellingRule: Optional
        Value: 190.0
  - Name: NetworkConfiguratorEditModels
    Type: BaseObjectType
  - Name: SystemNode
    Type: NodePointer
    DataType: NodeId
    Value: "/Objects/optix_example/System/System"
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/System"
  - Name: NetworkSettingsLogic
    Type: NetLogic
    Children:
    - Class: Method
      Name: ApplyNetworkConfiguration
    - Class: Method
      Name: Reboot
  - Name: NetworkInterfaceLogic
    Type: NetLogic
  - Name: NetworkConfiguratorEditModelsLogic
    Type: NetLogic
  - Name: NetworkInterfacesEditModelToSystemWriterLogic
    Type: NetLogic
  - Name: NetworkInterfacesEditModelReaderLogic
    Type: NetLogic
  - Name: SystemToNetworkInterfacesEditModelWriterLogic
    Type: NetLogic
- File: NetworkSettingsWidgetComponents/NetworkSettingsWidgetComponents.yaml
