Name: DeviceSettingsWidget
Type: FolderType
Children:
- Name: DeviceSettingsWidget
  Id: g=343e9a553a1648e3de95b91f6d877b43
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 240.0
  - Name: NavigationPanel1
    Type: NavigationPanel
    Children:
    - Name: Panels
      Type: BaseObjectType
      Children:
      - Name: Panel1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Configuration"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/optix_example/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Configuration"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel2
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"ProductInformation"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/optix_example/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Product_Information"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel3
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Diagnostics"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/optix_example/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Diagnostics"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
    - Name: CurrentPanel
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Children:
      - Name: Kind
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":6}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 304.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 240.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: BottomMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: CurrentTabIndex
      Type: BaseDataVariableType
      DataType: Int32
    - Class: Reference
      Target: ns=5;i=1181
    - Class: Reference
      Target: ns=5;i=1183
  - Name: SystemNode
    Type: NodePointer
    DataType: NodeId
    Value: "/Objects/optix_example/System/System"
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/System"
  - Name: DeviceSettingsWidgetLogic
    Type: NetLogic
- File: DeviceSettingsWidgetComponents/DeviceSettingsWidgetComponents.yaml
